default: &default
  adapter: postgresql
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cbook_dev

test:
  <<: *default
  database: cbook_test

production:
  <<: *default
  database: cbook_production
